### ISSUE TITLE
separate configuration from code

### ISSUE THREAD

**Issue by mwermelinger** [dsa-ou/allowed#10]
The configuration is currently part of the code. Anyone needing a different configuration has to edit every new version of `allowed.py`. Tedious and error-prone. 

The configuration must be separated into another file. As Tony suggested in #4, possibly a simple JSON file with the three dictionaries (`LANGUAGE`, `IMPORTS`  and `METHODS`) is enough, but using [TOML](https://realpython.com/python-toml) may also be a possibility.

To implement this:
- [ ] look up how to read JSON and TOML files in Python
- [ ] translate a small part of the current M269 configuration in `allowed.py` to both formats and present them here for discussion
- [ ] decide on a format
- [x] separate the M269 configuration into a `m269.json` or `m269.toml` file
- [x] add an option (e.g. `-c` or `--config`) that takes as argument the configuration file, which by default would be `m269.json` or `m269.toml`

**Comment by psychemedia** [comment]
Another possibility might be YAML, which is often used for config, though TOML may be more appropriate. One consideration might be: who might create such a file, and which would they find easier (and why...).

**Comment by mwermelinger** [comment]
If using TOML, do as in https://github.com/hukkin/tomli#building-a-tomlitomllib-compatibility-layer so that we can easily upgrade to Python 3.11 when pytype works with it.

**Comment by mwermelinger** [comment]
If using TOML, default configuration file should be named `pyproject.toml` with a section `[tool.allowed]`, as it happens with other tools, like `black` and `nbqa`.

**Comment by mwermelinger** [comment]
The core of this issue (separating the configuration) has been resolved in the commit mentioned above. Using TOML is a further enhancement (or complication) and can be discussed and addressed in a new issue.
