### ISSUE TITLE
"attribute" construct should be mapped to unit 2 in LANGUAGE

### ISSUE THREAD

**Issue by densnow** [dsa-ou/allowed#14]
Unit 2 introduced `math.pi`, `math.ceil`, `math.floor` and `math.trunc`. These are all examples of accessing attributes. Currently "attribute" is mapped to unit 4 in the `LANGUAGE` dict.

**Comment by mwermelinger** [comment]
Thanks. I also noticed a few other issues, which I have fixed but yet pushed.
