### ISSUE TITLE
nbqa still reports bad cells

### ISSUE THREAD

**Issue by mwermelinger** [dsa-ou/allowed#15]
Contrary to what the documentation of `nbqa` says, cells with wrong syntax or with line magics don't seem to be ignored but are instead passed to `allowed`, which then, for some reason, reports a disallowed use of built-in function `hash()` instead of reporting a syntax error. 

Once the default configuration allows the hash function in unit 8, these messages no longer appear.

**Comment by mwermelinger** [comment]
To be clear: with nbqa, `allowed` is working correctly: it checks all valid cells instead of skipping the whole notebook because of a syntax error. It's just annoying to have those meaningless messages about hashing.

**Comment by densnow** [comment]
I have had a look into this...

 A bit of experimenting shows that when using `nbqa` and `allowed` on an example `.ipynb` file say `02_4_assignments.ipynb`, the "source" that is passed to `allowed` is basically this:
```text
# %%NBQA-CELL-SEP05dc98
year = 2020
birth = 2010
age = year - birth


# %%NBQA-CELL-SEP05dc98
year = 2020
year                # not last line, so it isn't displayed
birth = 2010
age = year - birth
age                 # last line, so it's displayed


# %%NBQA-CELL-SEP05dc98
year = 2020
print(year)
birth = 2010
age = year - birth
age


# %%NBQA-CELL-SEP05dc98
current_year = 2020
year_of_birth = 2010
age = current_year - year_of_birth
print(age)


# %%NBQA-CELL-SEP05dc98
hash(0xEDEEF5BF)


# %%NBQA-CELL-SEP05dc98
currentyear     # current_year is defined, currentyear isn't


# %%NBQA-CELL-SEP05dc98
hash(0xF189E912)


# %%NBQA-CELL-SEP05dc98
hash(0xB919759F)


# %%NBQA-CELL-SEP05dc98
left-associative


# %%NBQA-CELL-SEP05dc98
# replace this by your code
```
After a superficial look at the `nbqa` source, the cause of our issue can be traced to [this line](https://github.com/nbQA-dev/nbQA/blob/26f3ce04cd29bdfcda487fefdbae78925e80a5ff/nbqa/handle_magics.py#L217) .  Don't know what we can do about it though, we might just have to live with the limitation. I have experimented with just replacing the hash with an empty string and it did still work for our purposes but would incapacitate the whole "cell magic" handing system (and god knows what else...).

**Comment by mwermelinger** [comment]
Great detective work, thanks! Given that you have implemented your own suggestion, I'll close this issue when PR #16 has been merged.
