### ISSUE TITLE
Check on Windows

### ISSUE THREAD

**Issue by mwermelinger** [dsa-ou/allowed#2]
The program was developed on macOS and should work on Linux, but it needs to be tried on Windows and the instructions may need updating.

**Comment by mwermelinger** [comment]
An earlier version was kindly tested on Windows by our tutor Andy Connolly, so the current one should also work, but it's best to keep this issue open for the moment. 

Although Andy was able to install `pytype` on WSL, it's also available in Anaconda and Miniconda. It remains to be seen if it works that way too.

**Comment by jrobsondev** [comment]
I have taken a further look into this and pytype is still not supported by Windows natively (see https://github.com/google/pytype/issues/1154).

I tried installing via Anaconda but had no luck. The only way to get it working is to use WSL as mentioned above.

**Comment by mwermelinger** [comment]
Thanks for trying this out and confirming the status quo. So the current README doesn't need updating and I'm hereby closing this issue.
