### ISSUE TITLE
Allow users to specify allowed operators

### ISSUE THREAD

**Issue by psychemedia** [dsa-ou/allowed#4]
It looks like you need to specify `ast.` elements to configure the tool with allowed elements at each level; it would be convenient to also allow users to specify to specify allowed elements using operator symbols (eg based on reversing the `OPERATORS` dictionary.

**Comment by mwermelinger** [comment]
Good point. Actually, the most user-friendly way would be to just use strings that describe the construct, e.g.

`LANGUAGE = {1: ['+', 'for'], 2: ['for-else', 'list comprehension'], ...}`

and then let the program convert everything to the corresponding `ast` classes. This would also make the FOR_ELSE and WHILE_ELSE constants obsolete: the code would just check if the strings `'for-else'` or `'while-else'` are in the allowed set.

**Comment by psychemedia** [comment]
A couple of other things I'd explore as a general tool would be loading the language definition from a JSON file (specified by an optional CLI parameter) and maybe even passing a list of operators in by a CLI argument (though I suspect folk are often confused about how to pass lists, dicts, etc in via CLI commands.

**Comment by mwermelinger** [comment]
This issue has been split into #5 and #10.
