### ISSUE TITLE
Type annotation on built in collection flagged as "unknown construct"

### ISSUE THREAD

**Issue by densnow** [dsa-ou/allowed#44]
When a type annotation is used on a built in collection type e.g.
```python
my_map: dict[int, int] = {}
my_tuple: tuple[int, int] = (1, 2)
my_list: list[int] = [1, 2] 
```
 `allowed` flags  the line and displays the "unknown construct" error message.

**Comment by mwermelinger** [comment]
Thanks. Without having looked at the code my guess is that the [AnnAssign node](https://docs.python.org/3/library/ast.html#ast.AnnAssign) needs to be handled. Needs of course a corresponding test in sample.py.

**Comment by mwermelinger** [comment]
Given that type annotations are not checked in function parameters, this should also be skipped.
