### ISSUE TITLE
Omit redundant/confusing warnings

### ISSUE THREAD

**Issue by densnow** [dsa-ou/allowed#58]
When `ipython` is not installed, a warning is printed that refers to notebook cells with magics. This warning is printed even when checking a `.py` which may potentially confuse the user.

Not a big deal, but I noticed it when doing `allowed sample.py` from within the test folder with a fresh venv without ipython installed.

**Comment by mwermelinger** [comment]
Great minds think alike :-) I had also noticed this and other redundant/confusing warnings:  
- user told to use -m even if pytype isn't installed or if no file was read (eg user gave folder w/o any .py and .ipynb)
- user warned about using -f even if no file was read

I had already started working on this.
