### ISSUE TITLE
improve test file

### ISSUE THREAD

**Issue by mwermelinger** [dsa-ou/allowed#8]
The [sample.py](../blob/main/sample.py) file that tests the checker is quite ad-hoc (and not comprehensive) in the coverage of constructs. It would be better to replace the file with smaller files, one per unit, that only use the constructs introduced in that unit. A file that uses all Python constructs not allowed in M269 is also needed.

- [ ] create a file `02-m269.py` that only uses the constructs introduced in unit 2, as defined in [allowed.py](../blob/main/allowed.py)
- [ ] create files `03-m269.py`, etc. Don't create files for units that introduce no constructs, like unit 5.
- [ ] create a file `33-m269.py` that uses some Python language constructs and builtin functions not allowed in M269, i.e. not defined in `allowed.py`. 
- [ ] run `python allowed.py *m269.py` and check that violations are only reported for `33-m269.py`

**Comment by densnow** [comment]
Do we still need these test files? I had writen a few of these, but then started to think they are very specific to M269 and the default configuration. Of course `allowed` was primary built for M269 (I am assuming) but we now have the ability to customise it through configuration.

**Comment by mwermelinger** [comment]
You're right. It's better to change `sample.py` so that it includes more Python constructs in a more concise way. Currently, the file has 'realistic' code, e.g. functions that actually compute something, but that leads to lots of repeated constructs and makes it harder to realise which constructs aren't covered. So the file should be more like
```py
1 + 2 - 3 * 4 // 5 % 6 ^ 7 
round(3 / 2, 3) 
... # more numeric ops and builtins
True and False or not False 
3 < 5 <= 7 > 6 >= 1  # comparisons
if 3 == 5:
    pass
elif 3 != 3:
    print("no")
else:
    ... # test some other construct
```
By including most (ultimately all) Python constructs in a single file, users could test it against their configuration with different unit numbers. The file only needs to contain all M269 constructs and a couple of other widely used constructs not used in M269, like +=, tuple unpacking, list comprehensions. Other users can then extend `sample.py` as they need.

**Comment by jurassic-squid** [comment]
@densnow I did have an idea for refactoring the `check_tree()` function and splitting the message creation and display into a separate class. I've put together a little demo script to show you how it could work:

```python
import ast
from _ast import AugAssign, Call
from typing import Any


STUDENT_CODE = """
animals = ['cat', 'dog', 'fish', 'bird']

def foo():
    for i, animal in enumerate(animals):
        print(i, animal)

animals += ['horse', 'cow', 'pig']        
"""

# This is just a simple example - we will categorise constructs further.
DISALLOWED_CONSTRUCTS = ['+=', 'enumerate']


class CLIMessenger:
    """This class will handle all of the command line output and the construction
    of messages that will be displayed to students."""

    def display_message(self, node: ast.AST) -> None:
        print(f"Found disallowed construct: {ast.dump(node)}")
    
    # We would obviously want to make this more sophisticated, with clearer messages.
    # We could have methods for each type of disallowed construct. We could even
    # consider using a library like rich to make the output more colorful and
    # easier to read. See https://rich.readthedocs.io/en/stable/introduction.html


class ConstructChecker(ast.NodeVisitor):
    """This class will replace the old check_tree function. It will be responsible
    for checking the AST for any disallowed constructs that are passed to its
    constructer. If a disallowed construct is found, the relevant information will
    be passed to the CLIMessenger class to be displayed to the student."""

    # The ast.NodeVisitor class has a generic visit method that will be called
    # for every node in the tree. We can override this method to check for
    # disallowed constructs. We can also override the visit_* methods for
    # specific nodes that we want to check for disallowed constructs.
    # See https://docs.python.org/3/library/ast.html#ast.NodeVisitor

    def __init__(
        self,
        disallowed_constructs: list[str],
        messenger: CLIMessenger
    ) -> None:
        self._disallowed_constructs = disallowed_constructs
        self._messenger = messenger
    
    def check_tree(self, tree: ast.AST) -> None:
        self.visit(tree)

    def visit_AugAssign(self, node: AugAssign) -> None:
        # We would check if the operator is in the list of disallowed constructs
        # here. For now, I just check if it is an addition for the sake of example.   
        if isinstance(node.op, ast.Add):
            self._messenger.display_message(node)
        self.generic_visit(node) # Visit all child nodes

    def visit_Call(self, node: Call) -> None:
        if isinstance(node.func, ast.Name) and node.func.id in self._disallowed_constructs:
            self._messenger.display_message(node)
        self.generic_visit(node)
                
    
def main():
    tree = ast.parse(STUDENT_CODE)
    messenger = CLIMessenger()
    checker = ConstructChecker(DISALLOWED_CONSTRUCTS, messenger)
    checker.check_tree(tree)


if __name__ == '__main__':
    main()  
```

Let me know what you think.

**Comment by jurassic-squid** [comment]
To get back on topic re testing...

What I can do is redo the sample file to include all constructs that are allowed in M269, plus some additional commonly-used constructs, but in a more systematic way, i.e. one construct per line with comment, so it's obvious which construct is being tested. Then I could create tests that will compare the ouput of allowed.py against some additional 'expected output' files. 

I would have to have an output file that matches the expected output when checking against each unit, with or without the `-m` tag and for both `.py` and `.ipynb` files. So there will likely be quite a few files to check against. 

Is that the kind of thing you had in mind? 

I could then automate the running of all test cases for all units.

**Comment by densnow** [comment]
@jurassic-squid @mwermelinger  Do you think it could be worthwhile to test different cases for each configuration? 

E.g. with the M269 config have:
 - a file that includes all the allowed M269 constructs and no more. The expected output would have no warnings.
 - a file that includes all the allowed M269 constructs plus some commonly used not allowed constructs. The expected output would be warnings from each not allowed construct.
  - a file that includes non of the M269 constructs plus some commonly used extras. The expected output would be warnings from the extras
 
I am trying to think in terms of edge cases for `allowed` and what they are. Can you think of anything else that might be considered an edge case?

There is also now a [tm112.json](https://github.com/dsa-ou/allowed/blob/main/tm112.json) configuration which can be used for testing. 

A couple of resources that might be of use here are the [exec_tests](https://github.com/python/cpython/blob/7703def37e4fa7d25c3d23756de8f527daa4e165/Lib/test/test_ast.py#L36) and [eval_tests](https://github.com/python/cpython/blob/7703def37e4fa7d25c3d23756de8f527daa4e165/Lib/test/test_ast.py#L194) lists used for testing the ast library. And of course the [ast documentation ](https://docs.python.org/3/library/ast.html)

**Comment by mwermelinger** [comment]
I think we should still keep a single sample.py test file, but be more systematic in terms of Python 3.10 coverage (we don't have to cover the advanced Python 3.10 stuff like async). One line per construct makes the file too long and it won't be needed once #29 is fixed. The file can be totally meaningless in terms of what it produces, e.g.
```
3 + 4 - 5 * 6 / 7 // 8 % 2 ** 3
while True:
    for i in range(10, 1, -1):
       if i > 10:
          pass
```
(The current sample.py is repetitive in what it tests.)

The test script should automatically search for all configurations (find all JSON files with a IMPORTS dict etc.), and for each configuration find which units introduce constructs, then run allowed for each of those units.

As now, the script can be run in generate mode (create the output file) or check mode (compare against existing output).

The test script can be improved independently of the sample file.

**Comment by mwermelinger** [comment]
This discussion has ranged wide and far beyond the scope of the issue. I'm closing it to open better scoped issues.
