### ISSUE TITLE
turn on method call checks

### ISSUE THREAD

**Issue by mwermelinger** [dsa-ou/allowed#9]
Currently, `allowed` checks method calls (which takes a long time) whenever possible (`pytype` is installed and the user is running Python 3.7–3.10). This doesn't allow to first do the quick checks, which cover most constructs, and only once those are fixed do  method call checks.

To support this, turn off method checks by default and add an option (e.g. `-m` and `--methods`) that turns it on. If turned on but the checks aren't possible, print the error messages as currently.

If method checks are off but could be done, remind the user of this new option after the program has run.

**Comment by densnow** [comment]
I would like to pick up this one up if you don't mind, getting used to the GitHub workflow again!

Looks like the documentation (i.e the README) would need updating once this is added, do you have any preferences or guidance for this? is this something that should be done along with the enhancement or will you be editing this as we go along?

**Comment by mwermelinger** [comment]
Thanks for helping out! I prefer whoever fixes an issue to also update the documentation. I think only the README section about method call checks will need to be updated.

**Comment by densnow** [comment]
How do you feel about printing all warnings and reminders to do with the method checking after the program has run? 

I have a  turn-on-method-call-checks branch currently printing warnings to do with Python version and installing `pytype` before the program has run (as before), and the reminder to use option` -m` or` --methods` (if it has not been used and can be) printing after the program has run. It seems like we could just print all of these warnings after the program has run where they are possibly easier to see and it could make the code a little less cluttered. Is there any reasons why this should not be done?

**Comment by mwermelinger** [comment]
You’re right that printing messages before the program runs might make the user miss them.
I suggest that if the user types `-m` but method checks aren’t possible, the program prints an error message (it’s not a warning any more) and ends, without doing any checks.
In terms of code, it’s indeed better to do all the error messaging in the main section.

From: densnow ***@***.***>
Date: Saturday, 25 February 2023 at 11:23
To: dsa-ou/allowed ***@***.***>
Cc: Michel.Wermelinger ***@***.***>, Author ***@***.***>
Subject: Re: [dsa-ou/allowed] turn on method call checks (Issue #9)

CAUTION: This mail comes from outside the University. Please consider this before opening attachments, clicking links, or acting on the content.

How do you feel about printing all warnings and reminders to do with the method checking after the program has run?

I have a turn-on-method-call-checks branch currently printing warnings to do with Python version and installing pytype before the program has run (as before), and the reminder to use option -m or --methods (if it has not been used and can be) printing after the program has run. It seems like we could just print all of these warnings after the program has run where they are possibly easier to see and it could make the code a little less cluttered. Is there any reasons why this should not be done?

**Comment by densnow** [comment]
Just noticed that `argparser.exit()` does not print implicit newline character causing mild annoyance of terminal prompt not being on newline after abrupt program exit. As far as I can tell for our purposes `argparser.exit()` and `sys.exit()` can serve the same purpose (unless I am missing something) and `sys.exit()` does end with implicit newline. Suggestions:  either replace instances of `argparser.exit()` with `sys.exit()` (which when given string argument results in exit code 1 as well) or append newline characters onto each error message.

I would vote for using sys.exit() unless there is a specific reason for the `argparser.exit()` ?

**Comment by mwermelinger** [comment]
I think I changed sys.exit to argparse.exit after reading more about both, but can't remember the reason. If argparse.exit is giving you that error, it's OK to change to sys.exit.

**Comment by densnow** [comment]
`argparse.exit()` only seems to do this when it has the exit code argument . I tried it with only the message and newline occurred as normal.
